// GENERATED by data/reference-dishes/build.py - do not edit by hand.
import type { ReferenceDishData } from "./types.js";

export const REFERENCE_DATA_VERSION = "56086845ba7fd022";

export const REFERENCE_DATA: ReferenceDishData = {
  "aliases": {
    "becsi szelet": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "beef broth": [
      "hu_marhahusleves"
    ],
    "beef soup": [
      "hu_marhahusleves"
    ],
    "breaded cutlet": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "breaded pork cutlet": [
      "hu_rantott_hus"
    ],
    "breaded pork cutlet with parsley potatoes": [
      "hu_rantott_hus__petrezselymes_burgonya"
    ],
    "breaded pork cutlet with rice": [
      "hu_rantott_hus__parolt_rizs"
    ],
    "chicken paprikash with dumplings": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "csirkepaprikas nokedlivel": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "disznoporkolt": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "fischsuppe": [
      "hu_halaszle"
    ],
    "fisherman s soup": [
      "hu_halaszle"
    ],
    "gefulltes kraut": [
      "hu_toltott_kaposzta"
    ],
    "goulash soup": [
      "hu_gulyasleves"
    ],
    "gulaschsuppe": [
      "hu_gulyasleves"
    ],
    "gulyas": [
      "hu_gulyasleves"
    ],
    "gulyas leves": [
      "hu_gulyasleves"
    ],
    "gulyasleves": [
      "hu_gulyasleves"
    ],
    "gulyassuppe": [
      "hu_gulyasleves"
    ],
    "halaszle": [
      "hu_halaszle"
    ],
    "halaszle passzirozott alappal": [
      "hu_halaszle"
    ],
    "hungarian beef soup": [
      "hu_marhahusleves"
    ],
    "hungarian fish soup": [
      "hu_halaszle"
    ],
    "hungarian fisherman s soup": [
      "hu_halaszle"
    ],
    "hungarian goulash": [
      "hu_gulyasleves"
    ],
    "hungarian goulash soup": [
      "hu_gulyasleves"
    ],
    "hungarian layered potato casserole": [
      "hu_rakott_krumpli"
    ],
    "hungarian lecso with frankfurters": [
      "hu_lecso_virslivel"
    ],
    "hungarian pork stew porkolt": [
      "hu_sertesporkolt"
    ],
    "hungarian pork stew porkolt with dumplings": [
      "hu_sertesporkolt__nokedli"
    ],
    "hungarian pork stew porkolt with parsley potatoes": [
      "hu_sertesporkolt__petrezselymes_burgonya"
    ],
    "hungarian pork stew porkolt with rice": [
      "hu_sertesporkolt__parolt_rizs"
    ],
    "hungarian stuffed cabbage": [
      "hu_toltott_kaposzta"
    ],
    "husleves": [
      "hu_marhahusleves"
    ],
    "kartoffelauflauf ungarisch": [
      "hu_rakott_krumpli"
    ],
    "krautwickel": [
      "hu_toltott_kaposzta"
    ],
    "layered potato casserole": [
      "hu_rakott_krumpli"
    ],
    "lecso": [
      "hu_lecso_virslivel"
    ],
    "lecso virslivel": [
      "hu_lecso_virslivel"
    ],
    "lecso with sausage": [
      "hu_lecso_virslivel"
    ],
    "letscho mit wiener wurstchen": [
      "hu_lecso_virslivel"
    ],
    "letscho mit wurstchen": [
      "hu_lecso_virslivel"
    ],
    "marha husleves": [
      "hu_marhahusleves"
    ],
    "marhagulyas": [
      "hu_gulyasleves"
    ],
    "marhahusleves": [
      "hu_marhahusleves"
    ],
    "marhahusleves hussal zoldseggel": [
      "hu_marhahusleves"
    ],
    "paniertes schweineschnitzel": [
      "hu_rantott_hus"
    ],
    "paniertes schweineschnitzel mit petersilienkartoffeln": [
      "hu_rantott_hus__petrezselymes_burgonya"
    ],
    "paniertes schweineschnitzel mit reis": [
      "hu_rantott_hus__parolt_rizs"
    ],
    "paprikahendl": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "paprikahuhn mit nockerln": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "paprikas csirke galuskaval": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "paprikas csirke nokedlivel": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "pork and sauerkraut stew": [
      "hu_szekelykaposzta"
    ],
    "pork porkolt": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "pork schnitzel": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "pork stew": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "porkolt": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "porkolt krumplival": [
      "hu_sertesporkolt__petrezselymes_burgonya"
    ],
    "porkolt nokedlivel": [
      "hu_sertesporkolt__nokedli"
    ],
    "porkolt rizzsel": [
      "hu_sertesporkolt__parolt_rizs"
    ],
    "rakott burgonya": [
      "hu_rakott_krumpli"
    ],
    "rakott krumpli": [
      "hu_rakott_krumpli"
    ],
    "rantott hus": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "rantott hus krumplival": [
      "hu_rantott_hus__petrezselymes_burgonya"
    ],
    "rantott hus petrezselymes krumplival": [
      "hu_rantott_hus__petrezselymes_burgonya"
    ],
    "rantott hus rizzsel": [
      "hu_rantott_hus__parolt_rizs"
    ],
    "rantott hus serteskaraj": [
      "hu_rantott_hus"
    ],
    "rantott hus serteskaraj parolt rizzsel": [
      "hu_rantott_hus__parolt_rizs"
    ],
    "rantott hus serteskaraj petrezselymes burgonyaval": [
      "hu_rantott_hus__petrezselymes_burgonya"
    ],
    "rantott szelet": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "rantotthus": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "rindfleischsuppe": [
      "hu_marhahusleves"
    ],
    "rindsuppe": [
      "hu_marhahusleves"
    ],
    "schnitzel": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "schweinegulasch": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "schweineporkolt": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "sertesporkolt": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "sertesporkolt galuskaval": [
      "hu_sertesporkolt__nokedli"
    ],
    "sertesporkolt nokedlivel": [
      "hu_sertesporkolt__nokedli"
    ],
    "sertesporkolt parolt rizzsel": [
      "hu_sertesporkolt__parolt_rizs"
    ],
    "sertesporkolt petrezselymes burgonyaval": [
      "hu_sertesporkolt__petrezselymes_burgonya"
    ],
    "stuffed cabbage": [
      "hu_toltott_kaposzta"
    ],
    "szegedi halaszle": [
      "hu_halaszle"
    ],
    "szegediner": [
      "hu_szekelykaposzta"
    ],
    "szegediner gulasch": [
      "hu_szekelykaposzta"
    ],
    "szekely cabbage pork and sauerkraut stew": [
      "hu_szekelykaposzta"
    ],
    "szekely goulash": [
      "hu_szekelykaposzta"
    ],
    "szekely kaposzta": [
      "hu_szekelykaposzta"
    ],
    "szekelygulyas": [
      "hu_szekelykaposzta"
    ],
    "szekelykaposzta": [
      "hu_szekelykaposzta"
    ],
    "toltott kaposzta": [
      "hu_toltott_kaposzta"
    ],
    "ungarische fischsuppe": [
      "hu_halaszle"
    ],
    "ungarische rindfleischsuppe": [
      "hu_marhahusleves"
    ],
    "ungarischer kartoffelauflauf": [
      "hu_rakott_krumpli"
    ],
    "ungarisches gefulltes kraut krautwickel": [
      "hu_toltott_kaposzta"
    ],
    "ungarisches schweineporkolt schweinegulasch": [
      "hu_sertesporkolt"
    ],
    "ungarisches schweineporkolt schweinegulasch mit nockerln": [
      "hu_sertesporkolt__nokedli"
    ],
    "ungarisches schweineporkolt schweinegulasch mit petersilienkartoffeln": [
      "hu_sertesporkolt__petrezselymes_burgonya"
    ],
    "ungarisches schweineporkolt schweinegulasch mit reis": [
      "hu_sertesporkolt__parolt_rizs"
    ],
    "virslis lecso": [
      "hu_lecso_virslivel"
    ],
    "wiener schnitzel vom schwein": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ]
  },
  "foodKeys": {
    "beef_shank": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "169441"
      },
      "hu": "marhalábszár"
    },
    "breadcrumbs": {
      "catalog": {
        "source": "bls",
        "sourceId": "B821000"
      },
      "hu": "zsemlemorzsa"
    },
    "butter": {
      "catalog": {
        "source": "open_database",
        "sourceId": "173430"
      },
      "hu": "vaj"
    },
    "caraway_seed": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "170918"
      },
      "hu": "kömény (egész/őrölt)"
    },
    "carp": {
      "catalog": {
        "source": "bls",
        "sourceId": "T501100"
      },
      "hu": "ponty"
    },
    "carrot": {
      "catalog": {
        "source": "bls",
        "sourceId": "G620100"
      },
      "hu": "sárgarépa"
    },
    "celeriac": {
      "catalog": {
        "source": "bls",
        "sourceId": "G660100"
      },
      "hu": "zellergumó"
    },
    "chicken_thigh_skin": {
      "catalog": {
        "source": "bls",
        "sourceId": "V4A5100"
      },
      "hu": "csirke felsőcomb bőrrel"
    },
    "egg": {
      "catalog": {
        "source": "bls",
        "sourceId": "E111100"
      },
      "hu": "tojás"
    },
    "frankfurter": {
      "catalog": {
        "source": "bls",
        "sourceId": "W211200"
      },
      "hu": "virsli"
    },
    "garlic": {
      "catalog": {
        "source": "bls",
        "sourceId": "G490100"
      },
      "hu": "fokhagyma"
    },
    "hot_pepper_fresh": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "2747660"
      },
      "hu": "cseresznyepaprika (erős)"
    },
    "kohlrabi": {
      "catalog": {
        "source": "bls",
        "sourceId": "G331100"
      },
      "hu": "karalábé"
    },
    "lard": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "171401"
      },
      "hu": "sertészsír"
    },
    "onion": {
      "catalog": {
        "source": "bls",
        "sourceId": "G480100"
      },
      "hu": "vöröshagyma"
    },
    "paprika_ground": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "171329"
      },
      "hu": "őrölt pirospaprika"
    },
    "parsley_leaf": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "170416"
      },
      "hu": "petrezselyemzöld"
    },
    "parsley_root": {
      "catalog": {
        "source": "bls",
        "sourceId": "G670100"
      },
      "hu": "petrezselyemgyökér"
    },
    "pork_loin": {
      "catalog": {
        "source": "bls",
        "sourceId": "U622100"
      },
      "hu": "sertéskaraj"
    },
    "pork_minced": {
      "catalog": {
        "source": "bls",
        "sourceId": "U020100"
      },
      "hu": "darált sertéshús"
    },
    "pork_shoulder": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "167843"
      },
      "hu": "sertéslapocka"
    },
    "potato": {
      "catalog": {
        "source": "bls",
        "sourceId": "K110100"
      },
      "hu": "burgonya"
    },
    "rice_white": {
      "catalog": {
        "source": "bls",
        "sourceId": "C352000"
      },
      "hu": "rizs (nyers)"
    },
    "sauerkraut": {
      "catalog": {
        "source": "bls",
        "sourceId": "G345100"
      },
      "hu": "savanyú káposzta"
    },
    "smoked_bacon": {
      "catalog": {
        "source": "bls",
        "sourceId": "W415000"
      },
      "hu": "füstölt szalonna / bacon"
    },
    "smoked_sausage": {
      "catalog": {
        "source": "bls",
        "sourceId": "W185000"
      },
      "hu": "füstölt kolbász (debreceni)"
    },
    "sour_cream": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "2346387"
      },
      "hu": "tejföl (20%)"
    },
    "sunflower_oil": {
      "catalog": {
        "source": "bls",
        "sourceId": "Q320000"
      },
      "hu": "napraforgóolaj"
    },
    "tomato": {
      "catalog": {
        "source": "bls",
        "sourceId": "G561100"
      },
      "hu": "paradicsom"
    },
    "wax_pepper": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "2747660"
      },
      "hu": "TV paprika / zöldpaprika"
    },
    "wheat_flour": {
      "catalog": {
        "source": "bls",
        "sourceId": "C214100"
      },
      "hu": "búzaliszt (BL55)"
    }
  },
  "variants": [
    {
      "densityGPerMl": 1.022,
      "dishId": "hu_gulyasleves",
      "id": "hu_gulyasleves",
      "ingredients": [
        {
          "foodKey": "beef_shank",
          "grams": 71.02,
          "role": "core"
        },
        {
          "foodKey": "potato",
          "grams": 71.02,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 29.59,
          "role": "core"
        },
        {
          "foodKey": "carrot",
          "grams": 23.67,
          "role": "core"
        },
        {
          "foodKey": "parsley_root",
          "grams": 11.84,
          "role": "core"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 11.84,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 11.84,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 3.55,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 1.18,
          "role": "seasoning"
        },
        {
          "foodKey": "garlic",
          "grams": 1.18,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.24,
          "role": "seasoning"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.022,
          "grams": 450,
          "part": "gulyasleves"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 450,
      "sources": [
        "https://streetkitchen.hu/receptek/klasszikus-gulyasleves",
        "https://www.mindmegette.hu/recept/hagyomanyos-gulyasleves-a-nagyi-is-igy-csinalta"
      ],
      "titles": {
        "de": "Gulaschsuppe",
        "en": "Hungarian goulash soup",
        "hu": "Gulyásleves"
      }
    },
    {
      "densityGPerMl": 1.01,
      "dishId": "hu_halaszle",
      "id": "hu_halaszle",
      "ingredients": [
        {
          "foodKey": "carp",
          "grams": 113.77,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 42.66,
          "role": "core"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 17.06,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 21.33,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 2.28,
          "role": "seasoning"
        },
        {
          "foodKey": "hot_pepper_fresh",
          "grams": 2.84,
          "role": "seasoning"
        },
        {
          "foodKey": "garlic",
          "grams": 1.42,
          "role": "seasoning"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.01,
          "grams": 500,
          "part": "halaszle"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 500,
      "sources": [
        "https://terebess.hu/tiszaorveny/recept/halaszle.html",
        "https://www.mindmegette.hu/recept/halaszle-eredeti"
      ],
      "titles": {
        "de": "Ungarische Fischsuppe",
        "en": "Hungarian fisherman's soup",
        "hu": "Halászlé (passzírozott alappal)"
      }
    },
    {
      "densityGPerMl": 1.017,
      "dishId": "hu_toltott_kaposzta",
      "id": "hu_toltott_kaposzta",
      "ingredients": [
        {
          "foodKey": "sauerkraut",
          "grams": 161.21,
          "role": "core"
        },
        {
          "foodKey": "pork_minced",
          "grams": 85.98,
          "role": "core"
        },
        {
          "foodKey": "rice_white",
          "grams": 12.9,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 16.12,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 1.07,
          "role": "seasoning"
        },
        {
          "foodKey": "egg",
          "grams": 5.37,
          "role": "core"
        },
        {
          "foodKey": "smoked_sausage",
          "grams": 21.5,
          "role": "core"
        },
        {
          "foodKey": "smoked_bacon",
          "grams": 16.12,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 2.15,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 1.29,
          "role": "seasoning"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 2.69,
          "role": "core"
        },
        {
          "foodKey": "sour_cream",
          "grams": 21.5,
          "role": "core"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.017,
          "grams": 450,
          "part": "toltott_kaposzta"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 450,
      "sources": [
        "https://sobors.hu/receptek/toltott-kaposzta-savanyu-kaposztabol-recept/",
        "https://streetkitchen.hu/receptek/klasszikus-csaladi-toltott-kaposzta",
        "https://www.mindmegette.hu/recept/klasszikus-toltott-kaposzta"
      ],
      "titles": {
        "de": "Ungarisches gefülltes Kraut (Krautwickel)",
        "en": "Hungarian stuffed cabbage",
        "hu": "Töltött káposzta"
      }
    },
    {
      "densityGPerMl": 0.893,
      "dishId": "hu_paprikas_csirke_nokedlivel",
      "id": "hu_paprikas_csirke_nokedlivel",
      "ingredients": [
        {
          "foodKey": "chicken_thigh_skin",
          "grams": 152.67,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 30.53,
          "role": "core"
        },
        {
          "foodKey": "sunflower_oil",
          "grams": 4.58,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 2.29,
          "role": "seasoning"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 15.27,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 15.27,
          "role": "core"
        },
        {
          "foodKey": "sour_cream",
          "grams": 38.17,
          "role": "core"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 90.01,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 32.61,
          "role": "core"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.024,
          "flatPlate": {
            "coverage": 0.4,
            "height_cm": 2.0
          },
          "grams": 300,
          "part": "paprikas_csirke"
        },
        {
          "densityGPerMl": 0.75,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.5
          },
          "grams": 200,
          "part": "nokedli"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 500,
      "sources": [
        "https://sobors.hu/receptek/tejfolos-csirkepaprikas-recept/",
        "https://www.mindmegette.hu/recept/paprikas-csirke-nokedli",
        "https://www.mindmegette.hu/recept/szaftos-paprikas-csirke-nokedlivel"
      ],
      "titles": {
        "de": "Paprikahuhn mit Nockerln",
        "en": "Chicken paprikash with dumplings",
        "hu": "Paprikás csirke nokedlivel"
      }
    },
    {
      "densityGPerMl": 1.039,
      "dishId": "hu_sertesporkolt",
      "id": "hu_sertesporkolt",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 221.24,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 66.37,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 6.64,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 3.32,
          "role": "seasoning"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 2.21,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.22,
          "role": "seasoning"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.039,
          "flatPlate": {
            "coverage": 0.45,
            "height_cm": 2.0
          },
          "grams": 300,
          "part": "sertesporkolt"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 300,
      "sources": [
        "https://streetkitchen.hu/receptek/a-tokeletes-sertesporkolt",
        "https://www.mindmegette.hu/recept/klasszikus-sertesporkolt"
      ],
      "titles": {
        "de": "Ungarisches Schweinepörkölt (Schweinegulasch)",
        "en": "Hungarian pork stew (pörkölt)",
        "hu": "Sertéspörkölt"
      }
    },
    {
      "densityGPerMl": 0.9,
      "dishId": "hu_sertesporkolt",
      "id": "hu_sertesporkolt__nokedli",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 221.24,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 66.37,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 6.64,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 3.32,
          "role": "seasoning"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 2.21,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.22,
          "role": "seasoning"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 86.96,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 32.61,
          "role": "core"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.039,
          "flatPlate": {
            "coverage": 0.45,
            "height_cm": 2.0
          },
          "grams": 300,
          "part": "sertesporkolt"
        },
        {
          "densityGPerMl": 0.75,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.5
          },
          "grams": 200,
          "part": "nokedli"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 500,
      "sources": [
        "https://streetkitchen.hu/receptek/a-tokeletes-sertesporkolt",
        "https://www.mindmegette.hu/recept/klasszikus-sertesporkolt",
        "https://www.mindmegette.hu/recept/paprikas-csirke-nokedli"
      ],
      "titles": {
        "de": "Ungarisches Schweinepörkölt (Schweinegulasch) mit Nockerln",
        "en": "Hungarian pork stew (pörkölt) with dumplings",
        "hu": "Sertéspörkölt nokedlivel"
      }
    },
    {
      "densityGPerMl": 0.87,
      "dishId": "hu_sertesporkolt",
      "id": "hu_sertesporkolt__petrezselymes_burgonya",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 221.24,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 66.37,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 6.64,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 3.32,
          "role": "seasoning"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 2.21,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.22,
          "role": "seasoning"
        },
        {
          "foodKey": "potato",
          "grams": 194.17,
          "role": "core"
        },
        {
          "foodKey": "butter",
          "grams": 7.77,
          "role": "core"
        },
        {
          "foodKey": "parsley_leaf",
          "grams": 1.94,
          "role": "garnish"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.039,
          "flatPlate": {
            "coverage": 0.45,
            "height_cm": 2.0
          },
          "grams": 300,
          "part": "sertesporkolt"
        },
        {
          "densityGPerMl": 0.7,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.5
          },
          "grams": 200,
          "part": "petrezselymes_burgonya"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 500,
      "sources": [
        "https://falatozz.hu/recept/petrezselymes-burgonya",
        "https://streetkitchen.hu/receptek/a-tokeletes-sertesporkolt",
        "https://streetkitchen.hu/receptek/klasszik-petrezselymes-burgonya",
        "https://www.mindmegette.hu/recept/klasszikus-sertesporkolt"
      ],
      "titles": {
        "de": "Ungarisches Schweinepörkölt (Schweinegulasch) mit Petersilienkartoffeln",
        "en": "Hungarian pork stew (pörkölt) with parsley potatoes",
        "hu": "Sertéspörkölt petrezselymes burgonyával"
      }
    },
    {
      "densityGPerMl": 0.934,
      "dishId": "hu_sertesporkolt",
      "id": "hu_sertesporkolt__parolt_rizs",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 221.24,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 72.84,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 6.64,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 3.32,
          "role": "seasoning"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 2.21,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.22,
          "role": "seasoning"
        },
        {
          "foodKey": "rice_white",
          "grams": 53.89,
          "role": "core"
        },
        {
          "foodKey": "sunflower_oil",
          "grams": 3.23,
          "role": "core"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.039,
          "flatPlate": {
            "coverage": 0.45,
            "height_cm": 2.0
          },
          "grams": 300,
          "part": "sertesporkolt"
        },
        {
          "densityGPerMl": 0.8,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.2
          },
          "grams": 180,
          "part": "parolt_rizs"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 480,
      "sources": [
        "https://borralfozok.hu/a-tokeletes-parolt-rizs/",
        "https://streetkitchen.hu/receptek/a-tokeletes-sertesporkolt",
        "https://tesco.hu/hello/receptek/parolt-rizs/278828/",
        "https://www.mindmegette.hu/recept/klasszikus-sertesporkolt"
      ],
      "titles": {
        "de": "Ungarisches Schweinepörkölt (Schweinegulasch) mit Reis",
        "en": "Hungarian pork stew (pörkölt) with rice",
        "hu": "Sertéspörkölt párolt rizzsel"
      }
    },
    {
      "densityGPerMl": 0.991,
      "dishId": "hu_lecso_virslivel",
      "id": "hu_lecso_virslivel",
      "ingredients": [
        {
          "foodKey": "wax_pepper",
          "grams": 201.01,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 100.5,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 37.69,
          "role": "core"
        },
        {
          "foodKey": "frankfurter",
          "grams": 100.5,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 7.54,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 1.51,
          "role": "seasoning"
        },
        {
          "foodKey": "garlic",
          "grams": 1.51,
          "role": "seasoning"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 0.991,
          "flatPlate": {
            "coverage": 0.75,
            "height_cm": 1.6
          },
          "grams": 400,
          "part": "lecso_virslivel"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 400,
      "sources": [
        "https://sobors.hu/receptek/lecso-virslivel-recept/",
        "https://sobors.hu/receptek/virslis-lecso-recept/"
      ],
      "titles": {
        "de": "Letscho mit Wiener Würstchen",
        "en": "Hungarian lecsó with frankfurters",
        "hu": "Lecsó virslivel"
      }
    },
    {
      "densityGPerMl": 1.051,
      "dishId": "hu_rakott_krumpli",
      "id": "hu_rakott_krumpli",
      "ingredients": [
        {
          "foodKey": "potato",
          "grams": 214.29,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 71.43,
          "role": "core"
        },
        {
          "foodKey": "smoked_sausage",
          "grams": 47.62,
          "role": "core"
        },
        {
          "foodKey": "sour_cream",
          "grams": 95.24,
          "role": "core"
        },
        {
          "foodKey": "butter",
          "grams": 4.76,
          "role": "core"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.051,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 3.2
          },
          "grams": 400,
          "part": "rakott_krumpli"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 400,
      "sources": [
        "https://streetkitchen.hu/receptek/szaftos-rakott-krumpli",
        "https://www.mindmegette.hu/recept/rakott-krumpli"
      ],
      "titles": {
        "de": "Ungarischer Kartoffelauflauf",
        "en": "Hungarian layered potato casserole",
        "hu": "Rakott krumpli"
      }
    },
    {
      "densityGPerMl": 1.016,
      "dishId": "hu_marhahusleves",
      "id": "hu_marhahusleves",
      "ingredients": [
        {
          "foodKey": "beef_shank",
          "grams": 84.61,
          "role": "core"
        },
        {
          "foodKey": "carrot",
          "grams": 31.73,
          "role": "core"
        },
        {
          "foodKey": "parsley_root",
          "grams": 21.15,
          "role": "core"
        },
        {
          "foodKey": "celeriac",
          "grams": 10.58,
          "role": "core"
        },
        {
          "foodKey": "kohlrabi",
          "grams": 15.86,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 10.58,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 0.53,
          "role": "seasoning"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.016,
          "grams": 450,
          "part": "marhahusleves"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 450,
      "sources": [
        "https://falatozz.hu/recept/marhahusleves",
        "https://mamakonyhaja.hu/receptek/marhahus-leves/"
      ],
      "titles": {
        "de": "Ungarische Rindfleischsuppe",
        "en": "Hungarian beef soup",
        "hu": "Marhahúsleves (hússal, zöldséggel)"
      }
    },
    {
      "densityGPerMl": 0.85,
      "dishId": "hu_rantott_hus",
      "id": "hu_rantott_hus",
      "ingredients": [
        {
          "foodKey": "pork_loin",
          "grams": 150.0,
          "role": "core"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 7.5,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "breadcrumbs",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "sunflower_oil",
          "grams": 15.0,
          "role": "core"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 0.85,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 1.8
          },
          "grams": 185,
          "part": "rantott_hus"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 185,
      "sources": [
        "https://foodandwine.hu/2010/10/05/a-rantott-szelet-keszitesenek-10-titka/",
        "https://kemenytojas.com/receptek/rantott-hus/"
      ],
      "titles": {
        "de": "Paniertes Schweineschnitzel",
        "en": "Breaded pork cutlet",
        "hu": "Rántott hús (sertéskaraj)"
      }
    },
    {
      "densityGPerMl": 0.765,
      "dishId": "hu_rantott_hus",
      "id": "hu_rantott_hus__petrezselymes_burgonya",
      "ingredients": [
        {
          "foodKey": "pork_loin",
          "grams": 150.0,
          "role": "core"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 7.5,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "breadcrumbs",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "sunflower_oil",
          "grams": 15.0,
          "role": "core"
        },
        {
          "foodKey": "potato",
          "grams": 194.17,
          "role": "core"
        },
        {
          "foodKey": "butter",
          "grams": 7.77,
          "role": "core"
        },
        {
          "foodKey": "parsley_leaf",
          "grams": 1.94,
          "role": "garnish"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 0.85,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 1.8
          },
          "grams": 185,
          "part": "rantott_hus"
        },
        {
          "densityGPerMl": 0.7,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.5
          },
          "grams": 200,
          "part": "petrezselymes_burgonya"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 385,
      "sources": [
        "https://falatozz.hu/recept/petrezselymes-burgonya",
        "https://foodandwine.hu/2010/10/05/a-rantott-szelet-keszitesenek-10-titka/",
        "https://kemenytojas.com/receptek/rantott-hus/",
        "https://streetkitchen.hu/receptek/klasszik-petrezselymes-burgonya"
      ],
      "titles": {
        "de": "Paniertes Schweineschnitzel mit Petersilienkartoffeln",
        "en": "Breaded pork cutlet with parsley potatoes",
        "hu": "Rántott hús (sertéskaraj) petrezselymes burgonyával"
      }
    },
    {
      "densityGPerMl": 0.825,
      "dishId": "hu_rantott_hus",
      "id": "hu_rantott_hus__parolt_rizs",
      "ingredients": [
        {
          "foodKey": "pork_loin",
          "grams": 150.0,
          "role": "core"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 7.5,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "breadcrumbs",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "sunflower_oil",
          "grams": 18.23,
          "role": "core"
        },
        {
          "foodKey": "rice_white",
          "grams": 53.89,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 6.47,
          "role": "core"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 0.85,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 1.8
          },
          "grams": 185,
          "part": "rantott_hus"
        },
        {
          "densityGPerMl": 0.8,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.2
          },
          "grams": 180,
          "part": "parolt_rizs"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 365,
      "sources": [
        "https://borralfozok.hu/a-tokeletes-parolt-rizs/",
        "https://foodandwine.hu/2010/10/05/a-rantott-szelet-keszitesenek-10-titka/",
        "https://kemenytojas.com/receptek/rantott-hus/",
        "https://tesco.hu/hello/receptek/parolt-rizs/278828/"
      ],
      "titles": {
        "de": "Paniertes Schweineschnitzel mit Reis",
        "en": "Breaded pork cutlet with rice",
        "hu": "Rántott hús (sertéskaraj) párolt rizzsel"
      }
    },
    {
      "densityGPerMl": 1.026,
      "dishId": "hu_szekelykaposzta",
      "id": "hu_szekelykaposzta",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 140.32,
          "role": "core"
        },
        {
          "foodKey": "sauerkraut",
          "grams": 140.32,
          "role": "core"
        },
        {
          "foodKey": "sour_cream",
          "grams": 56.13,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 2.1,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 28.06,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 2.1,
          "role": "seasoning"
        },
        {
          "foodKey": "garlic",
          "grams": 0.84,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.14,
          "role": "seasoning"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 2.81,
          "role": "core"
        }
      ],
      "parts": [
        {
          "densityGPerMl": 1.026,
          "grams": 450,
          "part": "szekelykaposzta"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 450,
      "sources": [
        "https://magyarkonyhaonline.hu/receptek/a-legfinomabb-szekelykaposzta",
        "https://www.mindmegette.hu/recept/szekelykaposzta"
      ],
      "titles": {
        "de": "Szegediner Gulasch",
        "en": "Székely cabbage (pork and sauerkraut stew)",
        "hu": "Székelykáposzta"
      }
    }
  ]
};
