// GENERATED by data/reference-dishes/build.py - do not edit by hand.
import type { ReferenceDishData } from "./types.js";

export const REFERENCE_DATA_VERSION = "04ea8d67744de18a";

export const REFERENCE_DATA: ReferenceDishData = {
  "aliases": {
    "becsi szelet": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "beef broth": [
      "hu_marhahusleves"
    ],
    "beef soup": [
      "hu_marhahusleves"
    ],
    "bratkartoffeln": [
      "de_bratkartoffeln"
    ],
    "bratkartoffeln mit speck": [
      "de_bratkartoffeln"
    ],
    "bratkartoffeln mit speck und zwiebeln": [
      "de_bratkartoffeln"
    ],
    "breaded cutlet": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "breaded pork cutlet": [
      "hu_rantott_hus"
    ],
    "breaded pork cutlet with parsley potatoes": [
      "hu_rantott_hus__petrezselymes_burgonya"
    ],
    "breaded pork cutlet with rice": [
      "hu_rantott_hus__parolt_rizs"
    ],
    "chicken paprikash with dumplings": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "csirkepaprikas nokedlivel": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "disznoporkolt": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "eierspeis": [
      "xx_eierspeis"
    ],
    "eierspeis aus 3 eiern": [
      "xx_eierspeis"
    ],
    "eierspeise": [
      "xx_eierspeis"
    ],
    "fischsuppe": [
      "hu_halaszle"
    ],
    "fisherman s soup": [
      "hu_halaszle"
    ],
    "fleischkasbrotchen": [
      "xx_leberkaessemmel"
    ],
    "fried potatoes with bacon": [
      "de_bratkartoffeln"
    ],
    "gefulltes kraut": [
      "hu_toltott_kaposzta"
    ],
    "german fried potatoes": [
      "de_bratkartoffeln"
    ],
    "german fried potatoes with bacon and onion": [
      "de_bratkartoffeln"
    ],
    "gerostete erdapfel": [
      "de_bratkartoffeln"
    ],
    "gerostete erdapfel mit speck": [
      "de_bratkartoffeln"
    ],
    "goulash soup": [
      "hu_gulyasleves"
    ],
    "gulaschsuppe": [
      "hu_gulyasleves"
    ],
    "gulyas": [
      "hu_gulyasleves"
    ],
    "gulyas leves": [
      "hu_gulyasleves"
    ],
    "gulyasleves": [
      "hu_gulyasleves"
    ],
    "gulyassuppe": [
      "hu_gulyasleves"
    ],
    "halaszle": [
      "hu_halaszle"
    ],
    "halaszle passzirozott alappal": [
      "hu_halaszle"
    ],
    "hungarian beef soup": [
      "hu_marhahusleves"
    ],
    "hungarian fish soup": [
      "hu_halaszle"
    ],
    "hungarian fisherman s soup": [
      "hu_halaszle"
    ],
    "hungarian goulash": [
      "hu_gulyasleves"
    ],
    "hungarian goulash soup": [
      "hu_gulyasleves"
    ],
    "hungarian layered potato casserole": [
      "hu_rakott_krumpli"
    ],
    "hungarian lecso with frankfurters": [
      "hu_lecso_virslivel"
    ],
    "hungarian pork stew porkolt": [
      "hu_sertesporkolt"
    ],
    "hungarian pork stew porkolt with dumplings": [
      "hu_sertesporkolt__nokedli"
    ],
    "hungarian pork stew porkolt with parsley potatoes": [
      "hu_sertesporkolt__petrezselymes_burgonya"
    ],
    "hungarian pork stew porkolt with rice": [
      "hu_sertesporkolt__parolt_rizs"
    ],
    "hungarian stuffed cabbage": [
      "hu_toltott_kaposzta"
    ],
    "husleves": [
      "hu_marhahusleves"
    ],
    "kartoffelauflauf ungarisch": [
      "hu_rakott_krumpli"
    ],
    "krautwickel": [
      "hu_toltott_kaposzta"
    ],
    "layered potato casserole": [
      "hu_rakott_krumpli"
    ],
    "leberkaese sandwich": [
      "xx_leberkaessemmel"
    ],
    "leberkasbrotchen": [
      "xx_leberkaessemmel"
    ],
    "leberkase roll": [
      "xx_leberkaessemmel"
    ],
    "leberkase zsemleben": [
      "xx_leberkaessemmel"
    ],
    "leberkasebrotchen": [
      "xx_leberkaessemmel"
    ],
    "leberkases zsemle": [
      "xx_leberkaessemmel"
    ],
    "leberkasesemmel": [
      "xx_leberkaessemmel"
    ],
    "leberkassemmel": [
      "xx_leberkaessemmel"
    ],
    "leberkassemmerl": [
      "xx_leberkaessemmel"
    ],
    "leberkasweck": [
      "xx_leberkaessemmel"
    ],
    "lecso": [
      "hu_lecso_virslivel"
    ],
    "lecso virslivel": [
      "hu_lecso_virslivel"
    ],
    "lecso with sausage": [
      "hu_lecso_virslivel"
    ],
    "letscho mit wiener wurstchen": [
      "hu_lecso_virslivel"
    ],
    "letscho mit wurstchen": [
      "hu_lecso_virslivel"
    ],
    "marha husleves": [
      "hu_marhahusleves"
    ],
    "marhagulyas": [
      "hu_gulyasleves"
    ],
    "marhahusleves": [
      "hu_marhahusleves"
    ],
    "marhahusleves hussal zoldseggel": [
      "hu_marhahusleves"
    ],
    "paniertes schweineschnitzel": [
      "hu_rantott_hus"
    ],
    "paniertes schweineschnitzel mit petersilienkartoffeln": [
      "hu_rantott_hus__petrezselymes_burgonya"
    ],
    "paniertes schweineschnitzel mit reis": [
      "hu_rantott_hus__parolt_rizs"
    ],
    "paprikahendl": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "paprikahuhn mit nockerln": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "paprikas csirke galuskaval": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "paprikas csirke nokedlivel": [
      "hu_paprikas_csirke_nokedlivel"
    ],
    "piritott burgonya": [
      "de_bratkartoffeln"
    ],
    "piritott burgonya szalonnaval es hagymaval": [
      "de_bratkartoffeln"
    ],
    "piritott krumpli": [
      "de_bratkartoffeln"
    ],
    "pork and sauerkraut stew": [
      "hu_szekelykaposzta"
    ],
    "pork porkolt": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "pork roast": [
      "at_schweinsbraten"
    ],
    "pork schnitzel": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "pork stew": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "porkolt": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "porkolt krumplival": [
      "hu_sertesporkolt__petrezselymes_burgonya"
    ],
    "porkolt nokedlivel": [
      "hu_sertesporkolt__nokedli"
    ],
    "porkolt rizzsel": [
      "hu_sertesporkolt__parolt_rizs"
    ],
    "rakott burgonya": [
      "hu_rakott_krumpli"
    ],
    "rakott krumpli": [
      "hu_rakott_krumpli"
    ],
    "rantott hus": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "rantott hus krumplival": [
      "hu_rantott_hus__petrezselymes_burgonya"
    ],
    "rantott hus petrezselymes krumplival": [
      "hu_rantott_hus__petrezselymes_burgonya"
    ],
    "rantott hus rizzsel": [
      "hu_rantott_hus__parolt_rizs"
    ],
    "rantott hus serteskaraj": [
      "hu_rantott_hus"
    ],
    "rantott hus serteskaraj parolt rizzsel": [
      "hu_rantott_hus__parolt_rizs"
    ],
    "rantott hus serteskaraj petrezselymes burgonyaval": [
      "hu_rantott_hus__petrezselymes_burgonya"
    ],
    "rantott szelet": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "rantotta": [
      "xx_eierspeis"
    ],
    "rantotthus": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "rindfleischsuppe": [
      "hu_marhahusleves"
    ],
    "rindsuppe": [
      "hu_marhahusleves"
    ],
    "roast pork": [
      "at_schweinsbraten"
    ],
    "roast pork shoulder": [
      "at_schweinsbraten"
    ],
    "ruhrei": [
      "xx_eierspeis"
    ],
    "ruhreier": [
      "xx_eierspeis"
    ],
    "schnitzel": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ],
    "schweinebraten": [
      "at_schweinsbraten"
    ],
    "schweinegulasch": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "schweineporkolt": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "schweinsbraten": [
      "at_schweinsbraten"
    ],
    "schweinsbratl": [
      "at_schweinsbraten"
    ],
    "scrambled egg": [
      "xx_eierspeis"
    ],
    "scrambled eggs": [
      "xx_eierspeis"
    ],
    "sertesporkolt": [
      "hu_sertesporkolt",
      "hu_sertesporkolt__nokedli",
      "hu_sertesporkolt__petrezselymes_burgonya",
      "hu_sertesporkolt__parolt_rizs"
    ],
    "sertesporkolt galuskaval": [
      "hu_sertesporkolt__nokedli"
    ],
    "sertesporkolt nokedlivel": [
      "hu_sertesporkolt__nokedli"
    ],
    "sertesporkolt parolt rizzsel": [
      "hu_sertesporkolt__parolt_rizs"
    ],
    "sertesporkolt petrezselymes burgonyaval": [
      "hu_sertesporkolt__petrezselymes_burgonya"
    ],
    "sertessult": [
      "at_schweinsbraten"
    ],
    "stuffed cabbage": [
      "hu_toltott_kaposzta"
    ],
    "sult serteslapocka": [
      "at_schweinsbraten"
    ],
    "sult serteslapocka schweinsbraten": [
      "at_schweinsbraten"
    ],
    "szegedi halaszle": [
      "hu_halaszle"
    ],
    "szegediner": [
      "hu_szekelykaposzta"
    ],
    "szegediner gulasch": [
      "hu_szekelykaposzta"
    ],
    "szekely cabbage pork and sauerkraut stew": [
      "hu_szekelykaposzta"
    ],
    "szekely goulash": [
      "hu_szekelykaposzta"
    ],
    "szekely kaposzta": [
      "hu_szekelykaposzta"
    ],
    "szekelygulyas": [
      "hu_szekelykaposzta"
    ],
    "szekelykaposzta": [
      "hu_szekelykaposzta"
    ],
    "tojasrantotta": [
      "xx_eierspeis"
    ],
    "toltott kaposzta": [
      "hu_toltott_kaposzta"
    ],
    "ungarische fischsuppe": [
      "hu_halaszle"
    ],
    "ungarische rindfleischsuppe": [
      "hu_marhahusleves"
    ],
    "ungarischer kartoffelauflauf": [
      "hu_rakott_krumpli"
    ],
    "ungarisches gefulltes kraut krautwickel": [
      "hu_toltott_kaposzta"
    ],
    "ungarisches schweineporkolt schweinegulasch": [
      "hu_sertesporkolt"
    ],
    "ungarisches schweineporkolt schweinegulasch mit nockerln": [
      "hu_sertesporkolt__nokedli"
    ],
    "ungarisches schweineporkolt schweinegulasch mit petersilienkartoffeln": [
      "hu_sertesporkolt__petrezselymes_burgonya"
    ],
    "ungarisches schweineporkolt schweinegulasch mit reis": [
      "hu_sertesporkolt__parolt_rizs"
    ],
    "virslis lecso": [
      "hu_lecso_virslivel"
    ],
    "wiener schnitzel vom schwein": [
      "hu_rantott_hus",
      "hu_rantott_hus__petrezselymes_burgonya",
      "hu_rantott_hus__parolt_rizs"
    ]
  },
  "chainProducts": [
    {
      "carbsPer100g": 19.7,
      "category": "burger",
      "chain": "McDonald's",
      "countries": [
        "AT"
      ],
      "fatPer100g": 12,
      "fiberPer100g": 1.7,
      "kcalPer100g": 231,
      "name": "Big Mac (McDonald's)",
      "names": {
        "de": "Big Mac (McDonald's)",
        "de-AT": "Big Mac (McDonald's)",
        "en": "Big Mac (McDonald's)",
        "hu": "Big Mac (McDonald's)"
      },
      "proteinPer100g": 11,
      "provenance": {
        "carbohydrateBasis": "total_from_available_plus_fiber",
        "countries": [
          "AT"
        ],
        "retrievedAt": "2026-09-27",
        "source": "McDonald's official nutrition table (AT)",
        "sourceUrl": "https://www.mcdonalds.at/produkt/big-mac",
        "valuesPer": "100 g"
      },
      "serving": {
        "confidence": 0.9,
        "grams": 235.5,
        "isEstimated": true,
        "key": "piece",
        "labels": {
          "de": "Stück",
          "de-AT": "Stück",
          "en": "piece",
          "hu": "darab"
        },
        "unit": "piece"
      },
      "sourceId": "mcdonalds-at:big-mac",
      "synonyms": {
        "de": [
          "big mac",
          "bigmac"
        ],
        "de-AT": [
          "big mac"
        ],
        "en": [
          "big mac"
        ],
        "hu": [
          "big mac",
          "bigmac"
        ]
      }
    }
  ],
  "foodAliases": [
    {
      "alias": "Paradeiser",
      "foodKey": "tomato",
      "locale": "de-AT",
      "normalizedAlias": "paradeiser"
    },
    {
      "alias": "Tomate",
      "foodKey": "tomato",
      "locale": "de",
      "normalizedAlias": "tomate"
    },
    {
      "alias": "Tomaten",
      "foodKey": "tomato",
      "locale": "de",
      "normalizedAlias": "tomaten"
    },
    {
      "alias": "paradicsom",
      "foodKey": "tomato",
      "locale": "hu",
      "normalizedAlias": "paradicsom"
    },
    {
      "alias": "pari",
      "foodKey": "tomato",
      "locale": "hu",
      "normalizedAlias": "pari"
    },
    {
      "alias": "tomato",
      "foodKey": "tomato",
      "locale": "en",
      "normalizedAlias": "tomato"
    },
    {
      "alias": "Erdäpfel",
      "foodKey": "potato",
      "locale": "de-AT",
      "normalizedAlias": "erdapfel"
    },
    {
      "alias": "Kartoffel",
      "foodKey": "potato",
      "locale": "de",
      "normalizedAlias": "kartoffel"
    },
    {
      "alias": "Kartoffeln",
      "foodKey": "potato",
      "locale": "de",
      "normalizedAlias": "kartoffeln"
    },
    {
      "alias": "burgonya",
      "foodKey": "potato",
      "locale": "hu",
      "normalizedAlias": "burgonya"
    },
    {
      "alias": "krumpli",
      "foodKey": "potato",
      "locale": "hu",
      "normalizedAlias": "krumpli"
    },
    {
      "alias": "potato",
      "foodKey": "potato",
      "locale": "en",
      "normalizedAlias": "potato"
    },
    {
      "alias": "Frankfurter",
      "foodKey": "frankfurter",
      "locale": "de-AT",
      "normalizedAlias": "frankfurter"
    },
    {
      "alias": "Wiener Würstchen",
      "foodKey": "frankfurter",
      "locale": "de",
      "normalizedAlias": "wiener wurstchen"
    },
    {
      "alias": "Wiener",
      "foodKey": "frankfurter",
      "locale": "de",
      "normalizedAlias": "wiener"
    },
    {
      "alias": "virsli",
      "foodKey": "frankfurter",
      "locale": "hu",
      "normalizedAlias": "virsli"
    },
    {
      "alias": "frankfurter",
      "foodKey": "frankfurter",
      "locale": "en",
      "normalizedAlias": "frankfurter"
    },
    {
      "alias": "Semmel",
      "foodKey": "wheat_roll",
      "locale": "de-AT",
      "normalizedAlias": "semmel"
    },
    {
      "alias": "Kaisersemmel",
      "foodKey": "wheat_roll",
      "locale": "de-AT",
      "normalizedAlias": "kaisersemmel"
    },
    {
      "alias": "Brötchen",
      "foodKey": "wheat_roll",
      "locale": "de",
      "normalizedAlias": "brotchen"
    },
    {
      "alias": "Schrippe",
      "foodKey": "wheat_roll",
      "locale": "de",
      "normalizedAlias": "schrippe"
    },
    {
      "alias": "Weck",
      "foodKey": "wheat_roll",
      "locale": "de",
      "normalizedAlias": "weck"
    },
    {
      "alias": "Weckle",
      "foodKey": "wheat_roll",
      "locale": "de",
      "normalizedAlias": "weckle"
    },
    {
      "alias": "Semmel",
      "foodKey": "wheat_roll",
      "locale": "de",
      "normalizedAlias": "semmel"
    },
    {
      "alias": "zsemle",
      "foodKey": "wheat_roll",
      "locale": "hu",
      "normalizedAlias": "zsemle"
    },
    {
      "alias": "zsömle",
      "foodKey": "wheat_roll",
      "locale": "hu",
      "normalizedAlias": "zsomle"
    },
    {
      "alias": "bread roll",
      "foodKey": "wheat_roll",
      "locale": "en",
      "normalizedAlias": "bread roll"
    }
  ],
  "foodKeys": {
    "beef_shank": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "169441"
      },
      "hu": "marhalábszár"
    },
    "breadcrumbs": {
      "catalog": {
        "source": "bls",
        "sourceId": "B821000"
      },
      "hu": "zsemlemorzsa"
    },
    "butter": {
      "catalog": {
        "source": "open_database",
        "sourceId": "173430"
      },
      "hu": "vaj"
    },
    "caraway_seed": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "170918"
      },
      "hu": "kömény (egész/őrölt)"
    },
    "carp": {
      "catalog": {
        "source": "bls",
        "sourceId": "T501100"
      },
      "hu": "ponty"
    },
    "carrot": {
      "catalog": {
        "source": "bls",
        "sourceId": "G620100"
      },
      "hu": "sárgarépa"
    },
    "celeriac": {
      "catalog": {
        "source": "bls",
        "sourceId": "G660100"
      },
      "hu": "zellergumó"
    },
    "chicken_thigh_skin": {
      "catalog": {
        "source": "bls",
        "sourceId": "V4A5100"
      },
      "hu": "csirke felsőcomb bőrrel"
    },
    "clarified_butter": {
      "catalog": {
        "source": "bls",
        "sourceId": "Q683000"
      },
      "hu": "tisztított vaj (ghí)"
    },
    "egg": {
      "catalog": {
        "source": "bls",
        "sourceId": "E111100"
      },
      "hu": "tojás"
    },
    "frankfurter": {
      "catalog": {
        "source": "bls",
        "sourceId": "W211200"
      },
      "hu": "virsli"
    },
    "garlic": {
      "catalog": {
        "source": "bls",
        "sourceId": "G490100"
      },
      "hu": "fokhagyma"
    },
    "hot_pepper_fresh": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "2747660"
      },
      "hu": "cseresznyepaprika (erős)"
    },
    "kohlrabi": {
      "catalog": {
        "source": "bls",
        "sourceId": "G331100"
      },
      "hu": "karalábé"
    },
    "lard": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "171401"
      },
      "hu": "sertészsír"
    },
    "leberkaese": {
      "catalog": {
        "source": "bls",
        "sourceId": "W233000"
      },
      "hu": "leberkäse (sütött hússajt)"
    },
    "mustard": {
      "catalog": {
        "source": "bls",
        "sourceId": "R132000"
      },
      "hu": "mustár"
    },
    "onion": {
      "catalog": {
        "source": "bls",
        "sourceId": "G480100"
      },
      "hu": "vöröshagyma"
    },
    "paprika_ground": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "171329"
      },
      "hu": "őrölt pirospaprika"
    },
    "parsley_leaf": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "170416"
      },
      "hu": "petrezselyemzöld"
    },
    "parsley_root": {
      "catalog": {
        "source": "bls",
        "sourceId": "G670100"
      },
      "hu": "petrezselyemgyökér"
    },
    "pork_loin": {
      "catalog": {
        "source": "bls",
        "sourceId": "U622100"
      },
      "hu": "sertéskaraj"
    },
    "pork_minced": {
      "catalog": {
        "source": "bls",
        "sourceId": "U020100"
      },
      "hu": "darált sertéshús"
    },
    "pork_shoulder": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "167843"
      },
      "hu": "sertéslapocka"
    },
    "potato": {
      "catalog": {
        "source": "bls",
        "sourceId": "K110100"
      },
      "hu": "burgonya"
    },
    "rice_white": {
      "catalog": {
        "source": "bls",
        "sourceId": "C352000"
      },
      "hu": "rizs (nyers)"
    },
    "sauerkraut": {
      "catalog": {
        "source": "bls",
        "sourceId": "G345100"
      },
      "hu": "savanyú káposzta"
    },
    "smoked_bacon": {
      "catalog": {
        "source": "bls",
        "sourceId": "W415000"
      },
      "hu": "füstölt szalonna / bacon"
    },
    "smoked_sausage": {
      "catalog": {
        "source": "bls",
        "sourceId": "W185000"
      },
      "hu": "füstölt kolbász (debreceni)"
    },
    "sour_cream": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "2346387"
      },
      "hu": "tejföl (20%)"
    },
    "sunflower_oil": {
      "catalog": {
        "source": "bls",
        "sourceId": "Q320000"
      },
      "hu": "napraforgóolaj"
    },
    "tomato": {
      "catalog": {
        "source": "bls",
        "sourceId": "G561100"
      },
      "hu": "paradicsom"
    },
    "wax_pepper": {
      "catalog": {
        "source": "usda_fdc",
        "sourceId": "2747660"
      },
      "hu": "TV paprika / zöldpaprika"
    },
    "wheat_flour": {
      "catalog": {
        "source": "bls",
        "sourceId": "C214100"
      },
      "hu": "búzaliszt (BL55)"
    },
    "wheat_roll": {
      "catalog": {
        "source": "bls",
        "sourceId": "B511000"
      },
      "hu": "zsemle"
    }
  },
  "inventory": {
    "AT": {},
    "DE": {},
    "HU": {
      "everyday": [
        "tükörtojás",
        "főtt tojás",
        "tojásos nokedli",
        "bundás kenyér",
        "melegszendvics",
        "sonkás szendvics",
        "sajtos szendvics",
        "felvágottas szendvics",
        "zsíros kenyér",
        "körözöttes kenyér",
        "tejbegríz",
        "zabkása",
        "müzli joghurttal",
        "joghurt gyümölccsel",
        "túrós reggeli",
        "virsli mustárral",
        "debreceni mustárral",
        "sült kolbász",
        "párizsis zsemle",
        "sonkás kifli",
        "sajtos pogácsa",
        "tepertős pogácsa",
        "kifli",
        "zsemle",
        "magvas zsemle",
        "túrós táska",
        "kakaós csiga",
        "lekváros bukta",
        "fánk",
        "palacsinta",
        "túrós palacsinta",
        "lekváros palacsinta",
        "tejfölös tészta",
        "pesto pasta",
        "spaghetti bolognese",
        "carbonara",
        "lasagne",
        "pizza margherita",
        "sonkás pizza",
        "görög saláta",
        "cézársaláta",
        "uborkasaláta",
        "paradicsomsaláta",
        "káposztasaláta",
        "franciasaláta",
        "majonézes kukoricasaláta",
        "rizs csirkemellel",
        "gombás rizottó",
        "zöldséges kuszkusz",
        "sült csirkecomb",
        "csirkepaprikás",
        "sült csirkemell",
        "rakott tészta",
        "rakott karfiol hétköznapi",
        "zöldborsófőzelék",
        "tökfőzelék",
        "krumplifőzelék",
        "lencsefőzelék",
        "spenótfőzelék",
        "finomfőzelék",
        "paradicsomos káposzta",
        "sárgaborsó-főzelék",
        "kelkáposzta-főzelék"
      ],
      "street_food": [
        "fokhagymás lángos",
        "sajtos-tejfölös lángos",
        "töltött lángos",
        "kürtőskalács",
        "sült kolbász kenyérrel",
        "hurka mustárral",
        "véres hurka",
        "májas hurka",
        "budapesti hot dog",
        "hot dog",
        "gyros pita",
        "gyros tál",
        "döner",
        "döner tál",
        "falafel wrap",
        "hamburger",
        "sajtos hamburger",
        "pulled pork szendvics",
        "szelet pizza",
        "tócsni",
        "lapcsánka",
        "hekk",
        "lángos hamburgerrel",
        "lángos csirkével",
        "lángos sonkával"
      ],
      "traditional": [
        "bajai halászlé",
        "tiszai halászlé",
        "újházi tyúkhúsleves",
        "palócleves",
        "Jókai-bableves",
        "bableves",
        "lencseleves",
        "sárgaborsó-leves",
        "krumplileves",
        "frankfurti leves",
        "tárkonyos raguleves",
        "gyümölcsleves",
        "meggyleves",
        "sütőtökkrémleves",
        "gombakrémleves",
        "tejfölös burgonyaleves",
        "marhapörkölt",
        "csirkepörkölt",
        "birkapörkölt",
        "vadpörkölt",
        "pacalpörkölt",
        "körömpörkölt",
        "csülökpörkölt",
        "harcsapaprikás",
        "bakonyi sertésszelet",
        "vadas marha",
        "tokány",
        "brassói aprópecsenye",
        "cigánypecsenye",
        "fasírt",
        "töltött paprika",
        "rakott kel",
        "rakott karfiol",
        "rakott zöldbab",
        "paprikás krumpli",
        "rizses hús",
        "tarhonyás hús",
        "hortobágyi palacsinta",
        "rántott sajt",
        "sült oldalas",
        "sült csülök",
        "tepsis csirke",
        "túrós csusza",
        "káposztás tészta",
        "krumplis tészta",
        "mákos tészta",
        "diós tészta",
        "grízes tészta",
        "szilvás gombóc",
        "túrógombóc",
        "somlói galuska",
        "Gundel-palacsinta",
        "halászlé tejföllel",
        "juhászos tokány",
        "székelygulyás",
        "savanyú tojásleves",
        "kapros túrós lepény",
        "mákos guba",
        "aranygaluska",
        "kelt rétes",
        "dobostorta",
        "rigójancsi",
        "zserbó"
      ]
    }
  },
  "servings": [
    {
      "confidence": 0.85,
      "countries": [
        "AT"
      ],
      "foodKey": "wheat_roll",
      "grams": 62.5,
      "isEstimated": false,
      "key": "piece_at",
      "labels": {
        "de": "Brötchen",
        "de-AT": "Semmel",
        "en": "bread roll",
        "hu": "zsemle"
      },
      "sources": [
        {
          "retrieved": "2026-09-27",
          "url": "https://www.spar.at/produktwelt/spar-bio-kaisersemmel-60g-g-p2020001325436"
        },
        {
          "retrieved": "2026-09-27",
          "url": "https://shop.billa.at/produkte/ja-natuerlich-kaisersemmel-00480904"
        }
      ],
      "unit": "piece"
    }
  ],
  "variants": [
    {
      "category": "traditional",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 1.022,
      "dishId": "hu_gulyasleves",
      "id": "hu_gulyasleves",
      "ingredients": [
        {
          "foodKey": "beef_shank",
          "grams": 71.02,
          "role": "core"
        },
        {
          "foodKey": "potato",
          "grams": 71.02,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 29.59,
          "role": "core"
        },
        {
          "foodKey": "carrot",
          "grams": 23.67,
          "role": "core"
        },
        {
          "foodKey": "parsley_root",
          "grams": 11.84,
          "role": "core"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 11.84,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 11.84,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 3.55,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 1.18,
          "role": "seasoning"
        },
        {
          "foodKey": "garlic",
          "grams": 1.18,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.24,
          "role": "seasoning"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.022,
          "grams": 450,
          "part": "gulyasleves"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 450,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://streetkitchen.hu/receptek/klasszikus-gulyasleves"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/hagyomanyos-gulyasleves-a-nagyi-is-igy-csinalta"
        }
      ],
      "tags": [
        "soup",
        "traditional"
      ],
      "titles": {
        "de": "Gulaschsuppe",
        "en": "Hungarian goulash soup",
        "hu": "Gulyásleves"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 1.01,
      "dishId": "hu_halaszle",
      "id": "hu_halaszle",
      "ingredients": [
        {
          "foodKey": "carp",
          "grams": 113.77,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 42.66,
          "role": "core"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 17.06,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 21.33,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 2.28,
          "role": "seasoning"
        },
        {
          "foodKey": "hot_pepper_fresh",
          "grams": 2.84,
          "role": "seasoning"
        },
        {
          "foodKey": "garlic",
          "grams": 1.42,
          "role": "seasoning"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.01,
          "grams": 500,
          "part": "halaszle"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 500,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://terebess.hu/tiszaorveny/recept/halaszle.html"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/halaszle-eredeti"
        }
      ],
      "tags": [
        "soup",
        "traditional",
        "fish"
      ],
      "titles": {
        "de": "Ungarische Fischsuppe",
        "en": "Hungarian fisherman's soup",
        "hu": "Halászlé (passzírozott alappal)"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 1.017,
      "dishId": "hu_toltott_kaposzta",
      "id": "hu_toltott_kaposzta",
      "ingredients": [
        {
          "foodKey": "sauerkraut",
          "grams": 161.21,
          "role": "core"
        },
        {
          "foodKey": "pork_minced",
          "grams": 85.98,
          "role": "core"
        },
        {
          "foodKey": "rice_white",
          "grams": 12.9,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 16.12,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 1.07,
          "role": "seasoning"
        },
        {
          "foodKey": "egg",
          "grams": 5.37,
          "role": "core"
        },
        {
          "foodKey": "smoked_sausage",
          "grams": 21.5,
          "role": "core"
        },
        {
          "foodKey": "smoked_bacon",
          "grams": 16.12,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 2.15,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 1.29,
          "role": "seasoning"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 2.69,
          "role": "core"
        },
        {
          "foodKey": "sour_cream",
          "grams": 21.5,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.017,
          "grams": 450,
          "part": "toltott_kaposzta"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 450,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://sobors.hu/receptek/toltott-kaposzta-savanyu-kaposztabol-recept/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://streetkitchen.hu/receptek/klasszikus-csaladi-toltott-kaposzta"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/klasszikus-toltott-kaposzta"
        }
      ],
      "tags": [
        "traditional"
      ],
      "titles": {
        "de": "Ungarisches gefülltes Kraut (Krautwickel)",
        "en": "Hungarian stuffed cabbage",
        "hu": "Töltött káposzta"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 0.893,
      "dishId": "hu_paprikas_csirke_nokedlivel",
      "id": "hu_paprikas_csirke_nokedlivel",
      "ingredients": [
        {
          "foodKey": "chicken_thigh_skin",
          "grams": 152.67,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 30.53,
          "role": "core"
        },
        {
          "foodKey": "sunflower_oil",
          "grams": 4.58,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 2.29,
          "role": "seasoning"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 15.27,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 15.27,
          "role": "core"
        },
        {
          "foodKey": "sour_cream",
          "grams": 38.17,
          "role": "core"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 90.01,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 32.61,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.024,
          "flatPlate": {
            "coverage": 0.4,
            "height_cm": 2.0
          },
          "grams": 300,
          "part": "paprikas_csirke"
        },
        {
          "densityGPerMl": 0.75,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.5
          },
          "grams": 200,
          "part": "nokedli"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 500,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://sobors.hu/receptek/tejfolos-csirkepaprikas-recept/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/paprikas-csirke-nokedli"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/szaftos-paprikas-csirke-nokedlivel"
        }
      ],
      "tags": [
        "traditional"
      ],
      "titles": {
        "de": "Paprikahuhn mit Nockerln",
        "en": "Chicken paprikash with dumplings",
        "hu": "Paprikás csirke nokedlivel"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 1.039,
      "dishId": "hu_sertesporkolt",
      "id": "hu_sertesporkolt",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 221.24,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 66.37,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 6.64,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 3.32,
          "role": "seasoning"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 2.21,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.22,
          "role": "seasoning"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.039,
          "flatPlate": {
            "coverage": 0.45,
            "height_cm": 2.0
          },
          "grams": 300,
          "part": "sertesporkolt"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 300,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://streetkitchen.hu/receptek/a-tokeletes-sertesporkolt"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/klasszikus-sertesporkolt"
        }
      ],
      "tags": [
        "traditional",
        "low-carb-friendly"
      ],
      "titles": {
        "de": "Ungarisches Schweinepörkölt (Schweinegulasch)",
        "en": "Hungarian pork stew (pörkölt)",
        "hu": "Sertéspörkölt"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 0.9,
      "dishId": "hu_sertesporkolt",
      "id": "hu_sertesporkolt__nokedli",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 221.24,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 66.37,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 6.64,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 3.32,
          "role": "seasoning"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 2.21,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.22,
          "role": "seasoning"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 86.96,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 32.61,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.039,
          "flatPlate": {
            "coverage": 0.45,
            "height_cm": 2.0
          },
          "grams": 300,
          "part": "sertesporkolt"
        },
        {
          "densityGPerMl": 0.75,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.5
          },
          "grams": 200,
          "part": "nokedli"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 500,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://streetkitchen.hu/receptek/a-tokeletes-sertesporkolt"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/klasszikus-sertesporkolt"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/paprikas-csirke-nokedli"
        }
      ],
      "tags": [
        "traditional",
        "low-carb-friendly"
      ],
      "titles": {
        "de": "Ungarisches Schweinepörkölt (Schweinegulasch) mit Nockerln",
        "en": "Hungarian pork stew (pörkölt) with dumplings",
        "hu": "Sertéspörkölt nokedlivel"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 0.87,
      "dishId": "hu_sertesporkolt",
      "id": "hu_sertesporkolt__petrezselymes_burgonya",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 221.24,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 66.37,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 6.64,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 3.32,
          "role": "seasoning"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 2.21,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.22,
          "role": "seasoning"
        },
        {
          "foodKey": "potato",
          "grams": 194.17,
          "role": "core"
        },
        {
          "foodKey": "butter",
          "grams": 7.77,
          "role": "core"
        },
        {
          "foodKey": "parsley_leaf",
          "grams": 1.94,
          "role": "garnish"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.039,
          "flatPlate": {
            "coverage": 0.45,
            "height_cm": 2.0
          },
          "grams": 300,
          "part": "sertesporkolt"
        },
        {
          "densityGPerMl": 0.7,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.5
          },
          "grams": 200,
          "part": "petrezselymes_burgonya"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 500,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://falatozz.hu/recept/petrezselymes-burgonya"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://streetkitchen.hu/receptek/a-tokeletes-sertesporkolt"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://streetkitchen.hu/receptek/klasszik-petrezselymes-burgonya"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/klasszikus-sertesporkolt"
        }
      ],
      "tags": [
        "traditional",
        "low-carb-friendly"
      ],
      "titles": {
        "de": "Ungarisches Schweinepörkölt (Schweinegulasch) mit Petersilienkartoffeln",
        "en": "Hungarian pork stew (pörkölt) with parsley potatoes",
        "hu": "Sertéspörkölt petrezselymes burgonyával"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 0.934,
      "dishId": "hu_sertesporkolt",
      "id": "hu_sertesporkolt__parolt_rizs",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 221.24,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 72.84,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 6.64,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 3.32,
          "role": "seasoning"
        },
        {
          "foodKey": "wax_pepper",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 22.12,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 2.21,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.22,
          "role": "seasoning"
        },
        {
          "foodKey": "rice_white",
          "grams": 53.89,
          "role": "core"
        },
        {
          "foodKey": "sunflower_oil",
          "grams": 3.23,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.039,
          "flatPlate": {
            "coverage": 0.45,
            "height_cm": 2.0
          },
          "grams": 300,
          "part": "sertesporkolt"
        },
        {
          "densityGPerMl": 0.8,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.2
          },
          "grams": 180,
          "part": "parolt_rizs"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 480,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://borralfozok.hu/a-tokeletes-parolt-rizs/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://streetkitchen.hu/receptek/a-tokeletes-sertesporkolt"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://tesco.hu/hello/receptek/parolt-rizs/278828/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/klasszikus-sertesporkolt"
        }
      ],
      "tags": [
        "traditional",
        "low-carb-friendly"
      ],
      "titles": {
        "de": "Ungarisches Schweinepörkölt (Schweinegulasch) mit Reis",
        "en": "Hungarian pork stew (pörkölt) with rice",
        "hu": "Sertéspörkölt párolt rizzsel"
      }
    },
    {
      "category": "everyday",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 0.991,
      "dishId": "hu_lecso_virslivel",
      "id": "hu_lecso_virslivel",
      "ingredients": [
        {
          "foodKey": "wax_pepper",
          "grams": 201.01,
          "role": "core"
        },
        {
          "foodKey": "tomato",
          "grams": 100.5,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 37.69,
          "role": "core"
        },
        {
          "foodKey": "frankfurter",
          "grams": 100.5,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 7.54,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 1.51,
          "role": "seasoning"
        },
        {
          "foodKey": "garlic",
          "grams": 1.51,
          "role": "seasoning"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 0.991,
          "flatPlate": {
            "coverage": 0.75,
            "height_cm": 1.6
          },
          "grams": 400,
          "part": "lecso_virslivel"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 400,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://sobors.hu/receptek/lecso-virslivel-recept/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://sobors.hu/receptek/virslis-lecso-recept/"
        }
      ],
      "tags": [
        "traditional",
        "lower-carb"
      ],
      "titles": {
        "de": "Letscho mit Wiener Würstchen",
        "en": "Hungarian lecsó with frankfurters",
        "hu": "Lecsó virslivel"
      }
    },
    {
      "category": "everyday",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 1.051,
      "dishId": "hu_rakott_krumpli",
      "id": "hu_rakott_krumpli",
      "ingredients": [
        {
          "foodKey": "potato",
          "grams": 214.29,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 71.43,
          "role": "core"
        },
        {
          "foodKey": "smoked_sausage",
          "grams": 47.62,
          "role": "core"
        },
        {
          "foodKey": "sour_cream",
          "grams": 95.24,
          "role": "core"
        },
        {
          "foodKey": "butter",
          "grams": 4.76,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.051,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 3.2
          },
          "grams": 400,
          "part": "rakott_krumpli"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 400,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://streetkitchen.hu/receptek/szaftos-rakott-krumpli"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/rakott-krumpli"
        }
      ],
      "tags": [
        "traditional",
        "higher-carb"
      ],
      "titles": {
        "de": "Ungarischer Kartoffelauflauf",
        "en": "Hungarian layered potato casserole",
        "hu": "Rakott krumpli"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 1.016,
      "dishId": "hu_marhahusleves",
      "id": "hu_marhahusleves",
      "ingredients": [
        {
          "foodKey": "beef_shank",
          "grams": 84.61,
          "role": "core"
        },
        {
          "foodKey": "carrot",
          "grams": 31.73,
          "role": "core"
        },
        {
          "foodKey": "parsley_root",
          "grams": 21.15,
          "role": "core"
        },
        {
          "foodKey": "celeriac",
          "grams": 10.58,
          "role": "core"
        },
        {
          "foodKey": "kohlrabi",
          "grams": 15.86,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 10.58,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 0.53,
          "role": "seasoning"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.016,
          "grams": 450,
          "part": "marhahusleves"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 450,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://falatozz.hu/recept/marhahusleves"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://mamakonyhaja.hu/receptek/marhahus-leves/"
        }
      ],
      "tags": [
        "soup",
        "traditional",
        "low-carb-friendly"
      ],
      "titles": {
        "de": "Ungarische Rindfleischsuppe",
        "en": "Hungarian beef soup",
        "hu": "Marhahúsleves (hússal, zöldséggel)"
      }
    },
    {
      "category": "everyday",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 0.85,
      "dishId": "hu_rantott_hus",
      "id": "hu_rantott_hus",
      "ingredients": [
        {
          "foodKey": "pork_loin",
          "grams": 150.0,
          "role": "core"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 7.5,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "breadcrumbs",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "sunflower_oil",
          "grams": 15.0,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 0.85,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 1.8
          },
          "grams": 185,
          "part": "rantott_hus"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 185,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://foodandwine.hu/2010/10/05/a-rantott-szelet-keszitesenek-10-titka/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://kemenytojas.com/receptek/rantott-hus/"
        }
      ],
      "tags": [
        "traditional",
        "fried"
      ],
      "titles": {
        "de": "Paniertes Schweineschnitzel",
        "en": "Breaded pork cutlet",
        "hu": "Rántott hús (sertéskaraj)"
      }
    },
    {
      "category": "everyday",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 0.765,
      "dishId": "hu_rantott_hus",
      "id": "hu_rantott_hus__petrezselymes_burgonya",
      "ingredients": [
        {
          "foodKey": "pork_loin",
          "grams": 150.0,
          "role": "core"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 7.5,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "breadcrumbs",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "sunflower_oil",
          "grams": 15.0,
          "role": "core"
        },
        {
          "foodKey": "potato",
          "grams": 194.17,
          "role": "core"
        },
        {
          "foodKey": "butter",
          "grams": 7.77,
          "role": "core"
        },
        {
          "foodKey": "parsley_leaf",
          "grams": 1.94,
          "role": "garnish"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 0.85,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 1.8
          },
          "grams": 185,
          "part": "rantott_hus"
        },
        {
          "densityGPerMl": 0.7,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.5
          },
          "grams": 200,
          "part": "petrezselymes_burgonya"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 385,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://falatozz.hu/recept/petrezselymes-burgonya"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://foodandwine.hu/2010/10/05/a-rantott-szelet-keszitesenek-10-titka/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://kemenytojas.com/receptek/rantott-hus/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://streetkitchen.hu/receptek/klasszik-petrezselymes-burgonya"
        }
      ],
      "tags": [
        "traditional",
        "fried"
      ],
      "titles": {
        "de": "Paniertes Schweineschnitzel mit Petersilienkartoffeln",
        "en": "Breaded pork cutlet with parsley potatoes",
        "hu": "Rántott hús (sertéskaraj) petrezselymes burgonyával"
      }
    },
    {
      "category": "everyday",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 0.825,
      "dishId": "hu_rantott_hus",
      "id": "hu_rantott_hus__parolt_rizs",
      "ingredients": [
        {
          "foodKey": "pork_loin",
          "grams": 150.0,
          "role": "core"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 7.5,
          "role": "core"
        },
        {
          "foodKey": "egg",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "breadcrumbs",
          "grams": 25.0,
          "role": "core"
        },
        {
          "foodKey": "sunflower_oil",
          "grams": 18.23,
          "role": "core"
        },
        {
          "foodKey": "rice_white",
          "grams": 53.89,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 6.47,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 0.85,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 1.8
          },
          "grams": 185,
          "part": "rantott_hus"
        },
        {
          "densityGPerMl": 0.8,
          "flatPlate": {
            "coverage": 0.35,
            "height_cm": 2.2
          },
          "grams": 180,
          "part": "parolt_rizs"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 365,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://borralfozok.hu/a-tokeletes-parolt-rizs/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://foodandwine.hu/2010/10/05/a-rantott-szelet-keszitesenek-10-titka/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://kemenytojas.com/receptek/rantott-hus/"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://tesco.hu/hello/receptek/parolt-rizs/278828/"
        }
      ],
      "tags": [
        "traditional",
        "fried"
      ],
      "titles": {
        "de": "Paniertes Schweineschnitzel mit Reis",
        "en": "Breaded pork cutlet with rice",
        "hu": "Rántott hús (sertéskaraj) párolt rizzsel"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "HU"
      ],
      "densityGPerMl": 1.026,
      "dishId": "hu_szekelykaposzta",
      "id": "hu_szekelykaposzta",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 140.32,
          "role": "core"
        },
        {
          "foodKey": "sauerkraut",
          "grams": 140.32,
          "role": "core"
        },
        {
          "foodKey": "sour_cream",
          "grams": 56.13,
          "role": "core"
        },
        {
          "foodKey": "lard",
          "grams": 2.1,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 28.06,
          "role": "core"
        },
        {
          "foodKey": "paprika_ground",
          "grams": 2.1,
          "role": "seasoning"
        },
        {
          "foodKey": "garlic",
          "grams": 0.84,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.14,
          "role": "seasoning"
        },
        {
          "foodKey": "wheat_flour",
          "grams": 2.81,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.026,
          "grams": 450,
          "part": "szekelykaposzta"
        }
      ],
      "servedIn": "deep_plate",
      "servingGrams": 450,
      "sources": [
        {
          "retrieved": "2026-09-26",
          "url": "https://magyarkonyhaonline.hu/receptek/a-legfinomabb-szekelykaposzta"
        },
        {
          "retrieved": "2026-09-26",
          "url": "https://www.mindmegette.hu/recept/szekelykaposzta"
        }
      ],
      "tags": [
        "traditional",
        "low-carb-friendly"
      ],
      "titles": {
        "de": "Szegediner Gulasch",
        "en": "Székely cabbage (pork and sauerkraut stew)",
        "hu": "Székelykáposzta"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "AT",
        "DE"
      ],
      "densityGPerMl": 1.055,
      "dishId": "at_schweinsbraten",
      "id": "at_schweinsbraten",
      "ingredients": [
        {
          "foodKey": "pork_shoulder",
          "grams": 239.28,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 30.63,
          "role": "core"
        },
        {
          "foodKey": "garlic",
          "grams": 2.3,
          "role": "seasoning"
        },
        {
          "foodKey": "caraway_seed",
          "grams": 0.77,
          "role": "seasoning"
        },
        {
          "foodKey": "lard",
          "grams": 5.74,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "de-AT",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 1.055,
          "flatPlate": {
            "coverage": 0.44,
            "height_cm": 1.6
          },
          "grams": 250,
          "part": "schweinsbraten"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 250,
      "sources": [
        {
          "retrieved": "2026-09-27",
          "url": "https://www.gutekueche.at/omas-schweinsbratenrezept-rezept-19875"
        },
        {
          "retrieved": "2026-09-27",
          "url": "https://www.gutekueche.at/saftiger-schweinsbraten-rezept-14744"
        }
      ],
      "tags": [
        "traditional",
        "roast",
        "low-carb-friendly"
      ],
      "titles": {
        "de": "Schweinebraten",
        "de-AT": "Schweinsbraten",
        "en": "Roast pork shoulder",
        "hu": "Sült sertéslapocka (Schweinsbraten)"
      }
    },
    {
      "category": "traditional",
      "countries": [
        "DE"
      ],
      "densityGPerMl": 0.65,
      "dishId": "de_bratkartoffeln",
      "id": "de_bratkartoffeln",
      "ingredients": [
        {
          "foodKey": "potato",
          "grams": 215.52,
          "role": "core"
        },
        {
          "foodKey": "smoked_bacon",
          "grams": 38.79,
          "role": "core"
        },
        {
          "foodKey": "onion",
          "grams": 34.48,
          "role": "core"
        },
        {
          "foodKey": "clarified_butter",
          "grams": 4.31,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "de-AT",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 0.65,
          "flatPlate": {
            "coverage": 0.45,
            "height_cm": 2.5
          },
          "grams": 250,
          "part": "bratkartoffeln"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 250,
      "sources": [
        {
          "retrieved": "2026-09-27",
          "url": "https://www.essen-und-trinken.de/rezepte/55725-rzpt-klassische-bratkartoffeln"
        },
        {
          "retrieved": "2026-09-27",
          "url": "https://www.gutekueche.de/bratkartoffeln-mit-speck-und-zwiebel-rezept-28363"
        }
      ],
      "tags": [
        "traditional",
        "fried",
        "higher-carb"
      ],
      "titles": {
        "de": "Bratkartoffeln mit Speck und Zwiebeln",
        "de-AT": "Geröstete Erdäpfel mit Speck",
        "en": "German fried potatoes with bacon and onion",
        "hu": "Pirított burgonya szalonnával és hagymával"
      }
    },
    {
      "category": "everyday",
      "countries": [
        "HU",
        "AT",
        "DE"
      ],
      "densityGPerMl": 0.55,
      "dishId": "xx_eierspeis",
      "id": "xx_eierspeis",
      "ingredients": [
        {
          "foodKey": "egg",
          "grams": 150.0,
          "role": "core"
        },
        {
          "foodKey": "butter",
          "grams": 8.0,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "de-AT",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 0.55,
          "flatPlate": {
            "coverage": 0.4,
            "height_cm": 2.0
          },
          "grams": 150,
          "part": "eierspeis"
        }
      ],
      "servedIn": "flat_plate",
      "servingGrams": 150,
      "sources": [
        {
          "retrieved": "2026-09-27",
          "url": "https://www.ichkoche.at/eierspeis-rezept-7727"
        },
        {
          "retrieved": "2026-09-27",
          "url": "https://www.mindmegette.hu/recept/rantotta"
        }
      ],
      "tags": [
        "breakfast",
        "eggs",
        "low-carb-friendly"
      ],
      "titles": {
        "de": "Rührei",
        "de-AT": "Eierspeis",
        "en": "Scrambled eggs",
        "hu": "Rántotta"
      }
    },
    {
      "category": "street_food",
      "countries": [
        "AT",
        "DE"
      ],
      "densityGPerMl": 0.464,
      "dishId": "xx_leberkaessemmel",
      "id": "xx_leberkaessemmel",
      "ingredients": [
        {
          "foodKey": "wheat_roll",
          "grams": 62.5,
          "role": "core"
        },
        {
          "foodKey": "leberkaese",
          "grams": 100.0,
          "role": "core"
        }
      ],
      "languages": [
        "hu",
        "de",
        "de-AT",
        "en"
      ],
      "parts": [
        {
          "densityGPerMl": 0.464,
          "grams": 162.5,
          "part": "leberkaessemmel"
        }
      ],
      "servedIn": "handheld",
      "servingGrams": 162.5,
      "sources": [
        {
          "retrieved": "2026-09-27",
          "url": "https://fddb.info/db/de/lebensmittel/durchschnittswert_leberkaessemmel_mit_100_gr_leberkaese/index.html"
        },
        {
          "retrieved": "2026-09-27",
          "url": "https://shop.billa.at/produkte/ja-natuerlich-kaisersemmel-00480904"
        },
        {
          "retrieved": "2026-09-27",
          "url": "https://www.spar.at/produktwelt/spar-bio-kaisersemmel-60g-g-p2020001325436"
        }
      ],
      "tags": [
        "street_food",
        "higher-carb"
      ],
      "titles": {
        "de": "Leberkäsbrötchen",
        "de-AT": "Leberkässemmel",
        "en": "Leberkäse roll",
        "hu": "Leberkäsés zsemle"
      }
    }
  ]
};
