// GENERATED by data/reference-dishes/build.py - do not edit by hand.
import type { GeneratedUnitWeight } from "./generic-unit-weights.js";

export const GENERATED_UNIT_WEIGHTS: Record<string, readonly GeneratedUnitWeight[]> = {
  "piece": [
    {
      "countries": [
        "AT"
      ],
      "grams": 62.5,
      "key": "bread_roll_at",
      "keywords": [
        "semmel",
        "semmeln",
        "kaisersemmel",
        "kaisersemmeln"
      ],
      "wholeWord": true
    }
  ]
};
